Repository prgrms-web-devcourse/Team-Forest-RG-BE, pull requests merged in 2022-08, with the labels that each got.

#34 [feat] User 도메인 엔티티 설계 - 리뷰 반영: 다시 올렸습니다
  src/main/java/com/prgrms/rg/domain/common/model/metadata/Bicycle.java
  src/main/java/com/prgrms/rg/domain/common/model/metadata/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/user/model/Introduction.java
  src/main/java/com/prgrms/rg/domain/user/model/Manner.java
  src/main/java/com/prgrms/rg/domain/user/model/Nickname.java
  src/main/java/com/prgrms/rg/domain/user/model/RiderProfile.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/domain/user/model/UserBicycle.java
Labels: 백엔드, Issue

#42 [refactor] oauth 관련 테이블 관리 주체 변경
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/model/OAuth2AuthorizedClient.java
Labels: 백엔드

#37 [feat] 경력, 실력 표시
  src/main/java/com/prgrms/rg/domain/user/application/NoSuchUserException.java
  src/main/java/com/prgrms/rg/domain/user/application/UserReadService.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserReadServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/Introduction.java
  src/main/java/com/prgrms/rg/domain/user/model/Manner.java
  src/main/java/com/prgrms/rg/domain/user/model/MannerLevel.java
  src/main/java/com/prgrms/rg/domain/user/model/Nickname.java
  src/main/java/com/prgrms/rg/domain/user/model/ProfileImage.java
  src/main/java/com/prgrms/rg/domain/user/model/RiderProfile.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/domain/user/model/UserBicycle.java
  src/main/java/com/prgrms/rg/domain/user/model/UserRepository.java
  src/main/java/com/prgrms/rg/domain/user/model/information/MannerInfo.java
  src/main/java/com/prgrms/rg/domain/user/model/information/RiderInfo.java
  src/main/java/com/prgrms/rg/domain/user/model/information/UserImageInfo.java
  src/main/java/com/prgrms/rg/domain/user/model/information/UserProfilePageInfo.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaUserRepository.java
  src/main/java/com/prgrms/rg/web/user/api/UserRestController.java
  src/main/java/com/prgrms/rg/web/user/api/UserRestControllerAdvice.java
  src/main/java/com/prgrms/rg/web/user/api/UserRestControllerV1.java
  src/main/java/com/prgrms/rg/web/user/results/ImageInfoResult.java
  src/main/java/com/prgrms/rg/web/user/results/MannerInfoResult.java
  src/main/java/com/prgrms/rg/web/user/results/RiderInfoResult.java
  src/main/java/com/prgrms/rg/web/user/results/UserProfileResult.java
Labels: 리뷰 요청, 백엔드, Issue

#51 [fix] 토큰 문제 해결 및 불필요 의존성 정리
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/prgrms/rg/domain/auth/application/dummy.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/Jwt.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/rg/domain/auth/model/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/prgrms/rg/domain/auth/model/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/prgrms/rg/domain/auth/model/OAuth2AuthorizedClient.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserServiceImpl.java
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/test/java/com/prgrms/rg/web/user/api/UserControllerTest.java
  src/test/resources/application.yml
Labels: 백엔드

#31 [test] 카카오 OAuth 적용 테스트
  build.gradle
  src/main/java/com/prgrms/rg/config/JwtConfigure.java
  src/main/java/com/prgrms/rg/config/WebConfig.java
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/Jwt.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/rg/domain/notification/application/dummy.java
  src/main/java/com/prgrms/rg/domain/notification/model/dummy.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/dummy.java
  src/main/java/com/prgrms/rg/domain/user/application/UserService.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/Manner.java
  src/main/java/com/prgrms/rg/domain/user/model/Nickname.java
  src/main/java/com/prgrms/rg/domain/user/model/RiderProfile.java
  src/main/java/com/prgrms/rg/domain/user/model/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/domain/user/model/UserRepository.java
  src/main/java/com/prgrms/rg/domain/user/model/dummy.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaUserRepository.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/requests/OAuthLoginRequest.java
  src/main/java/com/prgrms/rg/web/user/results/OAuthLoginResult.java
  src/main/java/com/prgrms/rg/web/user/results/UserDto.java
  src/main/resources/application-security.yml
  src/main/resources/application.yml
  src/test/java/com/prgrms/rg/web/user/api/UserControllerTest.java
  src/test/resources/application.yml
Labels: 리뷰 요청, 백엔드, 코칭 요청

#47 [feat] 이미지 처리 엔드포인트 추가, 비동기 이미지 처리 방식으로 변경
  src/main/java/com/prgrms/rg/RgApplication.java
  src/main/java/com/prgrms/rg/domain/common/file/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/prgrms/rg/domain/common/file/application/AsyncImageManager.java
  src/main/java/com/prgrms/rg/domain/common/file/application/FileManager.java
  src/main/java/com/prgrms/rg/domain/common/file/application/FileStore.java
  src/main/java/com/prgrms/rg/domain/common/file/application/ImageAttachManger.java
  src/main/java/com/prgrms/rg/domain/common/file/application/exception/EmptyFileException.java
  src/main/java/com/prgrms/rg/domain/common/file/application/exception/FileIOException.java
  src/main/java/com/prgrms/rg/domain/common/file/application/exception/IllegalFileExtensionException.java
  src/main/java/com/prgrms/rg/domain/common/file/application/exception/IllegalImageIdException.java
  src/main/java/com/prgrms/rg/domain/common/file/application/impl/AsyncMultipartImageFileManager.java
  src/main/java/com/prgrms/rg/domain/common/file/application/impl/ImageAttachManagerImpl.java
  src/main/java/com/prgrms/rg/domain/common/file/application/impl/MultipartFileManager.java
  src/main/java/com/prgrms/rg/domain/common/file/model/AttachedImage.java
  src/main/java/com/prgrms/rg/domain/common/file/model/AttachedImageRepository.java
  src/main/java/com/prgrms/rg/domain/common/file/model/FileRepository.java
  src/main/java/com/prgrms/rg/domain/common/file/model/ImageOwner.java
  src/main/java/com/prgrms/rg/domain/common/file/model/TemporaryImage.java
  src/main/java/com/prgrms/rg/domain/common/file/model/TemporaryImageRepository.java
  src/main/java/com/prgrms/rg/domain/common/model/DummyStoredFile.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPost.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSubSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingThumbnailImage.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/SubImage.java
  src/main/java/com/prgrms/rg/domain/user/model/ProfileImage.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/infrastructure/file/ImageDeleteEntityListener.java
  src/main/java/com/prgrms/rg/infrastructure/file/S3FileStore.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaAttachedImageRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaFileRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaTemporaryImageRepository.java
  src/main/java/com/prgrms/rg/web/file/api/ImageRestController.java
  src/main/java/com/prgrms/rg/web/file/api/ImageRestControllerAdvice.java
  src/main/java/com/prgrms/rg/web/file/api/ImageRestControllerV1.java
  src/test/java/com/prgrms/rg/infrastructure/file/FileStoreDummy.java
Labels: 리뷰 요청, 백엔드, Issue

#60 [feat] 민감 코드 제거 및 서비스 기능 추가
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/application/dummy.java
  src/main/java/com/prgrms/rg/domain/auth/model/dummy.java
  src/main/java/com/prgrms/rg/domain/common/application/dummy.java
  src/main/java/com/prgrms/rg/domain/common/file/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/prgrms/rg/domain/common/file/application/FileIOException.java
  src/main/java/com/prgrms/rg/domain/common/file/application/FileManager.java
  src/main/java/com/prgrms/rg/domain/common/file/application/IllegalFileExtensionException.java
  src/main/java/com/prgrms/rg/domain/common/file/application/impl/MultipartFileManager.java
  src/main/java/com/prgrms/rg/domain/common/file/model/FileRepository.java
  src/main/java/com/prgrms/rg/domain/common/file/model/ImageAttachable.java
  src/main/java/com/prgrms/rg/domain/common/file/model/StoredFile.java
  src/main/java/com/prgrms/rg/domain/common/model/DummyStoredFile.java
  src/main/java/com/prgrms/rg/domain/user/application/UserService.java
  src/main/java/com/prgrms/rg/domain/user/application/dummy.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserServiceImpl.java
  src/main/java/com/prgrms/rg/infrastructure/file/FileDeleteEntityListener.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaFileRepository.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/requests/OAuthLoginRequest.java
  src/main/java/com/prgrms/rg/web/user/results/OAuthLoginResult.java
  src/main/resources/application-security.yml
Labels: 백엔드, Issue

#58 [feat] 라이딩 모집 글 작성
  src/main/java/com/prgrms/rg/domain/common/model/metadata/Bicycle.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingConditionCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingMainCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingParticipantCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingSubCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/dummy.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/AddressCode.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingConditionSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingCreateManagement.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingMainSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingParticipantSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPost.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSubSection.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingPostRepository.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RestRidingPostCreateController.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingCreateDetailRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingCreateMainRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingPostCreateRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/dummy.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
  src/test/resources/data.sql
Labels: 리뷰 요청, 백엔드, Issue

#46 23-라이딩 참가 기능 구현
  src/main/java/com/prgrms/rg/domain/common/event/DomainEvent.java
  src/main/java/com/prgrms/rg/domain/common/event/DomainEventPublisher.java
  src/main/java/com/prgrms/rg/domain/notification/application/NotificationService.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationPushService.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/notification/model/Notification.java
  src/main/java/com/prgrms/rg/domain/notification/model/NotificationRepository.java
  src/main/java/com/prgrms/rg/domain/notification/model/NotificationType.java
  src/main/java/com/prgrms/rg/domain/notification/model/sse/SseConnector.java
  src/main/java/com/prgrms/rg/domain/notification/model/sse/SseEmitterRepository.java
  src/main/java/com/prgrms/rg/domain/notification/model/sse/SseNotificationSender.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingJoinService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingJoinFailException.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingParticipantRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostFinder.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostNotFoundException.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/dummy.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/event/RidingJoinEvent.java
  src/main/java/com/prgrms/rg/domain/user/application/UserReadService.java
  src/main/java/com/prgrms/rg/domain/user/application/dummy.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserReadServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/dummy.java
  src/main/java/com/prgrms/rg/infrastructure/event/SpringEventPublisher.java
  src/main/java/com/prgrms/rg/infrastructure/event/dummy.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaNotificationRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingParticipantRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/MemorySseEmitterRepository.java
  src/main/java/com/prgrms/rg/web/notification/api/NotificationController.java
  src/main/java/com/prgrms/rg/web/notification/api/SseConnectionController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RestRidingPostCreateController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinExceptionHandler.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/dummy.java
Labels: 리뷰 요청, 백엔드

#62 [release] main -> develop 동기화
  .github/workflows/CI-develop.yml
  .github/workflows/CICD-main.yml
  .gitignore
  dockerfile
  src/main/java/com/prgrms/rg/domain/user/model/Manner.java
  src/main/java/com/prgrms/rg/infrastructure/cloud/CriticalMessageSender.java
  src/main/resources/application-security.yml
Labels: 백엔드

#66 [hotfix] 배포 서버 Https 설정
  config/server_script
  src/main/resources/application-prod.yml
Labels: 백엔드

#67 [hotfix] 배포 서버 https 설정
  config/server_script
Labels: 백엔드

#72 [feat] issue 500 예외 처리 및 전송 컴포넌트, 테스트 전용 모듈들
  .github/workflows/CICD-main.yml
  .gitignore
  config/docker-compose.yml
  src/main/java/com/prgrms/rg/RgApplication.java
  src/main/java/com/prgrms/rg/config/JpaConfiguration.java
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/rg/web/common/GlobalControllerAdvice.java
  src/main/java/com/prgrms/rg/web/common/message/ExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/LocalSystemExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/OuterSystemExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/results/InternalServerErrorResult.java
  src/main/resources/application-prod.yml
  src/test/java/com/prgrms/rg/testutil/ControllerTest.java
  src/test/java/com/prgrms/rg/testutil/FakeRestController.java
  src/test/java/com/prgrms/rg/web/common/GlobalControllerAdviceTest.java
Labels: 리뷰 요청, 백엔드

#68 [feat] 민감 코드 제거 및 테스트 코드 작성
  src/main/java/com/prgrms/rg/config/JwtConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/rg/domain/user/application/UserService.java
  src/main/java/com/prgrms/rg/domain/user/application/dummy.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserServiceImpl.java
  src/main/java/com/prgrms/rg/web/file/api/ImageRestControllerAdvice.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/results/UserDto.java
  src/main/java/com/prgrms/rg/web/user/results/UserMeResult.java
  src/test/java/com/prgrms/rg/domain/user/model/UserRepositoryTest.java
  src/test/java/com/prgrms/rg/web/user/api/UserControllerTest.java
  src/test/resources/application-test.yml
Labels: 백엔드, Issue

#73 [chore] profile 관리 방식 변경
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/resources/application-common.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
  src/test/resources/application.yml
Labels: 리뷰 요청, 백엔드

#75 [refactor] issue 라이딩 모집 글 작성 보완
  src/main/java/com/prgrms/rg/domain/common/file/model/AttachedImage.java
  src/main/java/com/prgrms/rg/domain/common/model/metadata/Bicycle.java
  src/main/java/com/prgrms/rg/domain/common/model/metadata/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingJoinService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingConditionCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingMainCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/AddressCode.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/AddressCodeRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/BicycleRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/Coordinate.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingConditionSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingCreateManagement.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingMainSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPost.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostFinder.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/RidingJoinFailException.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/RidingPostNotFoundException.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaAddressCodeRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaBicycleRepository.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RestRidingPostCreateController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingCreateExceptionHandler.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinExceptionHandler.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingCreateDetailRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingCreateMainRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingPostCreateRequest.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RestRidingPostCreateControllerTest.java
  src/test/resources/data.sql
Labels: 리뷰 요청, 백엔드, Issue

#80 [fix] 생성자 추가
  src/main/java/com/prgrms/rg/domain/user/application/dummy.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingCreateDetailRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingCreateMainRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingPostCreateRequest.java
Labels: 백엔드

#83 [feat] 인증 로직 유저 로직 나누기
  src/main/java/com/prgrms/rg/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/prgrms/rg/domain/user/application/UserAuthenticationService.java
  src/main/java/com/prgrms/rg/domain/user/application/UserService.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/infrastructure/oauth/KakaoOauth.java
  src/main/java/com/prgrms/rg/infrastructure/oauth/OAuthManager.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/requests/OAuthLoginRequest.java
  src/main/java/com/prgrms/rg/web/user/results/OAuthLoginResult.java
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImplTest.java
  src/test/java/com/prgrms/rg/web/user/api/UserControllerTest.java
Labels: 리뷰 요청, 백엔드

#84 [feat]50-라이딩상세 조회(#50)
  src/main/java/com/prgrms/rg/domain/common/model/metadata/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationPushService.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostReadService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingJoinService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/AddressCode.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingConditionBicycle.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingConditionSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingParticipantSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostFinder.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostInfo.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSubSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/RidingPostNotFoundException.java
  src/main/java/com/prgrms/rg/domain/user/model/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingInquiryController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinExceptionHandler.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryExceptionHandler.java
  src/main/resources/static/db/address_code.sql
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImplTest.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
  src/test/java/com/prgrms/rg/testutil/TestEntityDataFactory.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RestRidingPostCreateControllerTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingInquiryControllerTest.java
  src/test/resources/address_code.sql
  src/test/resources/bicycle.sql
  src/test/resources/data.sql
Labels: 리뷰 요청, 백엔드

#85 [feat] 서버 기본 json 에러 출력 컨트롤러
  src/main/java/com/prgrms/rg/web/common/CustomErrorController.java
  src/main/java/com/prgrms/rg/web/common/GlobalControllerAdvice.java
  src/main/java/com/prgrms/rg/web/common/results/GlobalServerErrorResult.java
  src/main/java/com/prgrms/rg/web/common/results/InternalServerErrorResult.java
  src/test/java/com/prgrms/rg/web/common/CustomErrorControllerTest.java
Labels: 리뷰 요청, 백엔드

#86 [feat] 회원 정보 수정
  src/main/java/com/prgrms/rg/domain/common/model/metadata/Bicycle.java
  src/main/java/com/prgrms/rg/domain/common/model/metadata/BicycleRepository.java
  src/main/java/com/prgrms/rg/domain/common/model/metadata/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/BicycleRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingCreateManagement.java
  src/main/java/com/prgrms/rg/domain/user/application/UserCommandService.java
  src/main/java/com/prgrms/rg/domain/user/application/command/UserUpdateCommand.java
  src/main/java/com/prgrms/rg/domain/user/application/exception/DuplicateNicknameException.java
  src/main/java/com/prgrms/rg/domain/user/application/exception/NoSuchUserException.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserCommandServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserReadServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/Nickname.java
  src/main/java/com/prgrms/rg/domain/user/model/RiderProfile.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/domain/user/model/UserBicycle.java
  src/main/java/com/prgrms/rg/domain/user/model/UserRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaBicycleRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaUserRepository.java
  src/main/java/com/prgrms/rg/web/common/RgControllerAdvice.java
  src/main/java/com/prgrms/rg/web/user/api/UserCommandRestControllerV1.java
  src/main/java/com/prgrms/rg/web/user/api/UserReadRestControllerV1.java
  src/main/java/com/prgrms/rg/web/user/api/UserRestControllerAdvice.java
  src/main/java/com/prgrms/rg/web/user/requests/UserUpdateRequest.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImplTest.java
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserCommandServiceImplTest.java
  src/test/java/com/prgrms/rg/web/user/api/UserCommandRestControllerV1Test.java
Labels: 리뷰 요청, 백엔드, Issue

#95 [fix] 이미지 저장 로직 수정
  src/main/java/com/prgrms/rg/domain/common/file/model/AttachedImage.java
Labels: 리뷰 요청, 백엔드, Issue

#94 [feat] 추가 회원가입 폼 생성
  src/main/java/com/prgrms/rg/domain/common/model/metadata/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/user/application/UserAuthenticationService.java
  src/main/java/com/prgrms/rg/domain/user/application/command/UserRegisterCommand.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/domain/user/model/dto/UserRegisterDTO.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/requests/UserRegisterRequest.java
  src/main/java/com/prgrms/rg/web/user/results/UserMeResult.java
  src/main/java/com/prgrms/rg/web/user/results/UserRegisterResult.java
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImplTest.java
  src/test/java/com/prgrms/rg/domain/user/model/UserTest.java
  src/test/java/com/prgrms/rg/web/user/api/UserControllerTest.java
  src/test/java/com/prgrms/rg/web/user/api/UserControllerUnitTest.java
Labels: 리뷰 요청, 백엔드

#97 [feat] 라이딩 모집 댓글 작성
  src/main/java/com/prgrms/rg/domain/common/RelatedEntityNotFoundException.java
  src/main/java/com/prgrms/rg/domain/notification/application/dummy.java
  src/main/java/com/prgrms/rg/domain/notification/model/dummy.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostCommentService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingPostCommentCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostComment.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/web/common/results/CommandSuccessResult.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentExceptionHandler.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingPostCommentCreateRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/results/dummy.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImplTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentControllerTest.java
Labels: 리뷰 요청, 백엔드

#100 [feat] 라이딩 댓글 작성 및 조회
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostCommentService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/command/RidingPostCommentCreateCommand.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/information/RidingPostCommentInfo.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostComment.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/RidingPostNotFoundException.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingPostRepository.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentController.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingPostCommentCreateRequest.java
  src/main/java/com/prgrms/rg/web/ridingpost/results/RidingPostCommentListResult.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImplTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentControllerTest.java
Labels: 백엔드, Issue

#105 [refactor] 프론트에 맞춰 리팩토링
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingMainSection.java
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingSaveMainRequest.java
  src/main/resources/static/db/bicycle.sql
Labels: 백엔드, Issue

#104 [feat] 87-라이딩 전체 조회
  src/main/java/com/prgrms/rg/domain/common/model/metadata/RidingLevel.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationPushService.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostReadService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingJoinService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostSearchRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSearchCondition.java
  src/main/java/com/prgrms/rg/infrastructure/repository/QuerydslRidingPostSearchRepository.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingInquiryController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryController.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImplTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryControllerTest.java
Labels: 백엔드

#110 [feat] issue 라이딩 모집 글 삭제
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/UnAuthorizedException.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostExceptionHandler.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostControllerTest.java
  src/test/resources/data.sql
Labels: 백엔드, Issue

#114 [fix] 107-상관없음-이슈대응
  src/main/java/com/prgrms/rg/domain/common/model/metadata/Bicycle.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSaveManagement.java
  src/main/java/com/prgrms/rg/infrastructure/repository/QuerydslRidingPostSearchRepository.java
  src/main/resources/static/db/bicycle.sql
  src/test/resources/bicycle.sql
Labels: 리뷰 요청, 백엔드

#116 [fix] 기본 Admin 데이터에 누락된 RiderProfile 정보 추가
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
Labels: 백엔드, Issue

#117 [feat] 라이딩 댓글 수정 및 삭제
  src/main/java/com/prgrms/rg/domain/ridingpost/application/RidingPostCommentService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/information/RidingPostCommentInfo.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/web/common/GlobalControllerAdvice.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentController.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImplTest.java
  src/test/java/com/prgrms/rg/testutil/FakeRestController.java
  src/test/java/com/prgrms/rg/web/common/GlobalControllerAdviceTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentControllerTest.java
Labels: 백엔드

#120 [chore] 서버 배포 버전 => develop 브랜치 동기화(2022.08.12 01:46 기준)
  .github/workflows/CICD-main.yml
  src/main/java/com/prgrms/rg/RgApplication.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/RidingLevel.java
  src/main/java/com/prgrms/rg/web/common/GlobalControllerAdvice.java
  src/main/java/com/prgrms/rg/web/common/message/CriticalMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/ExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/LocalSystemExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/MessageFactory.java
  src/main/java/com/prgrms/rg/web/common/message/OuterSystemExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/file/api/ImageRestControllerAdvice.java
  src/test/java/com/prgrms/rg/web/common/GlobalControllerAdviceTest.java
Labels: 백엔드

#121 [feat] jwt 만료 기능 및 refresh token
  src/main/java/com/prgrms/rg/config/WebSecurityConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/JwtRefreshToken.java
  src/main/java/com/prgrms/rg/domain/auth/JwtRefreshTokenRepository.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/AddressCodeRepository.java
  src/main/java/com/prgrms/rg/domain/user/application/UserAuthenticationService.java
  src/main/java/com/prgrms/rg/domain/user/application/command/UserRegisterCommand.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/RiderProfile.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/domain/user/model/dto/UserRegisterDTO.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaJwtRefreshTokenRepository.java
  src/main/java/com/prgrms/rg/web/common/GlobalControllerAdvice.java
  src/main/java/com/prgrms/rg/web/common/results/GlobalServerErrorResult.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/requests/UserRegisterRequest.java
  src/main/java/com/prgrms/rg/web/user/results/UserMeResult.java
  src/main/resources/application-common.yml
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImplTest.java
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserCommandServiceImplTest.java
  src/test/java/com/prgrms/rg/domain/user/model/UserTest.java
Labels: 리뷰 요청, 백엔드

#126 [fix] orphanremoval 로직 수정
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/test/java/com/prgrms/rg/domain/user/model/UserTest.java
Labels: 백엔드

#128 [fix] ridingpost의 image 처리 오류 해결
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingThumbnailImage.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
Labels: 백엔드, Issue

#122 [feat] 87 라이딩 전체조회 수정
  src/main/java/com/prgrms/rg/domain/common/model/metadata/BicycleRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/AddressCodeRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingParticipantSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSearchCondition.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSearchConditionValidator.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/RidingSearchFailException.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaAddressCodeRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/QuerydslRidingPostSearchRepository.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryExceptionHandler.java
  src/main/resources/static/db/address_code.sql
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostReadServiceImplTest.java
  src/test/java/com/prgrms/rg/infrastructure/repository/QuerydslRidingPostSearchRepositoryTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryControllerTest.java
  src/test/resources/address_code.sql
  src/test/resources/bicycle.sql
Labels: 백엔드

#134 [fix] 프론트 요구사항에 맞춘 로직 수정
  src/main/java/com/prgrms/rg/config/JwtConfigure.java
  src/main/java/com/prgrms/rg/domain/auth/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/web/user/api/UserController.java
  src/main/java/com/prgrms/rg/web/user/requests/UserRegisterRequest.java
  src/main/java/com/prgrms/rg/web/user/results/UserMeResult.java
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImplTest.java
  src/test/java/com/prgrms/rg/domain/user/model/UserTest.java
  src/test/java/com/prgrms/rg/web/user/api/UserControllerTest.java
Labels: 백엔드

#135 [feat] 전역 validation 예외 처리 controlleradvice
  src/main/java/com/prgrms/rg/web/common/GlobalControllerAdvice.java
  src/main/java/com/prgrms/rg/web/common/message/ExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/LocalSystemExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/common/message/MessageFactory.java
  src/main/java/com/prgrms/rg/web/common/message/OuterSystemExceptionMessageSender.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostController.java
  src/main/java/com/prgrms/rg/web/user/api/UserCommandRestControllerV1.java
  src/main/java/com/prgrms/rg/web/user/requests/UserUpdateRequest.java
  src/test/java/com/prgrms/rg/web/user/api/UserCommandRestControllerV1Test.java
Labels: 백엔드, Issue

#136 [fix] 잘못된 User 초기값 변경
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
Labels: 백엔드

#138 [fix] 부모 댓글 삭제 -> 자식 댓글 삭제
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostComment.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingPostCommentRepository.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentController.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostCommentServiceImplTest.java
Labels: 백엔드

#140 [fix] ridingpost의 image 처리 오류 해결
  src/main/java/com/prgrms/rg/domain/common/file/application/ImageAttachManager.java
  src/main/java/com/prgrms/rg/domain/common/file/application/impl/ImageAttachManagerImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImpl.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingImageSaveManagement.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPost.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPostRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSaveManagement.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSubSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingSubSectionRepository.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/SubImage.java
  src/main/java/com/prgrms/rg/infrastructure/repository/JpaRidingSubSectionRepository.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
Labels: 백엔드, Issue

#141 [fix] address code 추가
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/resources/static/db/address_code.sql
  src/test/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImplTest.java
Labels: 백엔드

#143 [Fix] introduction NPE처리
  src/main/java/com/prgrms/rg/domain/user/model/User.java
Labels: 백엔드, Issue

#139 [feat] 133 라이딩 참가 취소
  src/main/java/com/prgrms/rg/domain/notification/model/Notification.java
  src/main/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingJoinService.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingParticipantSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPost.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/event/RidingJoinCancelEvent.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/CancelDeadlineOverException.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/exception/RidingJoinCancelFailException.java
  src/main/java/com/prgrms/rg/web/common/results/ErrorResult.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinController.java
  src/main/java/com/prgrms/rg/web/ridingpost/api/RidingJoinExceptionHandler.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingJoinServiceTest.java
  src/test/java/com/prgrms/rg/testutil/TestEntityDataFactory.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingJoinControllerTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostCommentControllerTest.java
  src/test/java/com/prgrms/rg/web/ridingpost/api/RidingPostInquiryControllerTest.java
Labels: 백엔드

#146 [feat] 평가
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingParticipant.java
  src/main/java/com/prgrms/rg/domain/user/application/UserEvaluateService.java
  src/main/java/com/prgrms/rg/domain/user/application/command/EvaluatedFromMemberCommand.java
  src/main/java/com/prgrms/rg/domain/user/application/command/ParticipantEvaluateCommand.java
  src/main/java/com/prgrms/rg/domain/user/application/exception/EvaluationFailException.java
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserEvaluateServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/Manner.java
  src/main/java/com/prgrms/rg/domain/user/model/UserEvaluateManagement.java
  src/main/java/com/prgrms/rg/web/user/api/UserEvaluateController.java
  src/main/java/com/prgrms/rg/web/user/api/UserEvaluateControllerAdvice.java
  src/main/java/com/prgrms/rg/web/user/requests/ParticipantEvaluateRequest.java
  src/main/java/com/prgrms/rg/web/user/requests/RidingEvaluateRequest.java
  src/test/java/com/prgrms/rg/domain/user/application/UserEvaluateServiceTest.java
  src/test/java/com/prgrms/rg/testutil/TestEntityDataFactory.java
  src/test/java/com/prgrms/rg/web/user/api/UserEvaluateControllerTest.java
  src/test/resources/riding_post.sql
Labels: 백엔드, Issue

#147 [hotfix] 배포용 임시 데이터
  src/main/java/com/prgrms/rg/config/DataInitializer.java
Labels: 백엔드

#161 [fix] route 페치 조인 경로에 추가
  src/main/java/com/prgrms/rg/infrastructure/repository/QuerydslRidingPostSearchRepository.java
Labels: 백엔드, Issue

#158 [fix] ProfileImage 수정
  src/main/java/com/prgrms/rg/domain/user/application/impl/UserAuthenticationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/user/model/User.java
  src/main/java/com/prgrms/rg/infrastructure/oauth/KakaoOauth.java
  src/test/java/com/prgrms/rg/domain/user/model/UserRepositoryTest.java
  src/test/resources/evaluation_data.sql
Labels: 백엔드

#167 [fix] 시간 포맷 수정
  src/main/java/com/prgrms/rg/web/ridingpost/requests/RidingSaveMainRequest.java
Labels: 백엔드, Issue

#169 [chore] 프론트 테스트용 평가자 토큰 전송
  src/main/java/com/prgrms/rg/config/DataInitializer.java
Labels: 백엔드

#179 [feat] 내 알림 전체조회, 삭제 기능 구현
  src/main/java/com/prgrms/rg/domain/notification/application/NotificationService.java
  src/main/java/com/prgrms/rg/domain/notification/application/impl/NotificationServiceImpl.java
  src/main/java/com/prgrms/rg/domain/notification/model/NotificationInfo.java
  src/main/java/com/prgrms/rg/web/notification/api/NotificationController.java
  src/test/java/com/prgrms/rg/domain/notification/application/impl/NotificationServiceImplTest.java
Labels: Issue

#187 [fix] ridingpost 수정 시 dummy insert 해결
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingConditionBicycle.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingConditionSection.java
  src/main/java/com/prgrms/rg/domain/ridingpost/model/RidingPost.java
  src/test/java/com/prgrms/rg/domain/ridingpost/application/impl/RidingPostServiceImplTest.java
Labels: 백엔드, Issue

#192 [fix] setting 보안 관련 점검
  .github/workflows/CICD-main.yml
  config/server_script
Labels: 백엔드

#194 [docs] RestDocs에 유저 조회 / 유저 관련 라이딩 정보 추가
  src/test/java/com/prgrms/rg/web/user/api/UserReadRestControllerV1Test.java
Labels: 백엔드, Issue
